###

#peli
GET http://localhost:3000/trailers

### 

# Filtrar trailers por género
GET http://localhost:3000/trailers?genero=Drama
Accept: application/json

###

# Buscar trailers por actor
GET http://localhost:3000/trailers/actor?actor=Tom Hopper
Accept: application/json

###

# Obtener series con más de X temporadas
GET http://localhost:3000/trailers/temp?minTemporadas=3
Accept: application/json

###

# Crear un nuevo trailer
POST http://localhost:3000/trailers
Content-Type: application/json

{
    "titulo": "Nuevo Trailer",
    "categoria": "Serie",
    "genero": ["Acción", "Aventura"],
    "reparto": ["Actor 1", "Actor 2"],
    "resumen": "Este es un trailer de ejemplo",
    "trailer": "https://www.example.com/trailer"
}

###

# Eliminar un trailer
DELETE http://localhost:3000/trailers/672d1420cb11aa24a963a6
Accept: application/json

###

# Manejo de error - Trailer no encontrado
GET http://localhost:3000/trailers/9999
Accept: application/json
